honojs/vite-plugins

- packages/dev-server/README.md
- packages/dev-server/src/dev-server.ts
- packages/dev-server/test/e2e.test.ts
- packages/dev-server/test/mock/worker.ts
- packages/dev-server/test/public/static/hello.json
- packages/dev-server/test/vite.config.ts
> feat(dev-server): support `c.env.ASSETS` for CF Pages

- .changeset/chatty-toes-carry.md
- packages/cloudflare-pages/src/cloudflare-pages.ts
- packages/cloudflare-pages/test/cloudflare-pages.test.ts
`outputDir` option exists but is not referenced in the production code.
This PR adds `build.outDir` to the plugin config to respect `outputDir` option.
> fix(cloudflare-pages): respect `outputDir` option

- .changeset/five-emus-develop.md
- packages/dev-server/src/cloudflare-pages/cloudflare-pages.ts
Fix an issue where Miniflare's initialization process was executed on every access if use `options.cf`  in the `@hono/vite-dev-server` package.
> fix(dev-server): initialize Miniflare only on the first run

- packages/cloudflare-pages/src/cloudflare-pages.ts
We are using this plugin over at @lipu-linku, and we recently ran into a problem where the `entry` defaults screwed us over, since we are building a regular REST API, and not a React client side app.
This PR adds very simple JSDoc to the options, to allow users to see their default values in their editor, instead of having to look them up in a subfolder of a monorepo.
> Added JSDoc default values to the Cloudflare Pages plugin options

- .changeset/chatty-moose-remain.md
- packages/ssg/README.md
- packages/ssg/src/ssg.ts
- packages/ssg/test/ssg.test.ts
Based on research in honojs/honox#48
before: Use Vite to build the toSSG generated code. This means that it was built **twice**.
after: Generate a page with toSSG. That's it.
> feat(ssg): make it simple

- .changeset/wicked-starfishes-switch.md
- packages/dev-server/README.md
- packages/dev-server/src/dev-server.ts
Would be nice if there were a way to configure the export name. This would be useful to avoid conflict in cases where some runtimes (ie. Vercel Serverless) also rely on a default export.
e.g.
```ts
// ./api/index.ts
import { Hono } from 'hono'
import { handle } from 'hono/vercel'
export const runtime = 'edge';
export const app = new Hono().basePath('/api')
app.get('/hello', (c) => {
return c.json({
message: 'Hello Vercel!',
})
})
export const GET = handle(app)
export const POST = handle(app)
```
```ts
// ./vite.config.ts
import devServer from '@hono/vite-dev-server'
import { defineConfig } from 'vite'
export default defineConfig({
plugins: [
devServer({
entry: './api/index.ts',
export: 'app'
}),
]
})
```
> feat: add `export` option

- packages/dev-server/e2e/e2e.test.ts
- packages/dev-server/e2e/mock/worker.ts
- packages/dev-server/e2e/vite.config.ts
- packages/dev-server/e2e/wrangler.toml
- packages/dev-server/package.json
- packages/dev-server/src/cloudflare-pages/cloudflare-pages.ts
- packages/dev-server/src/dev-server.ts
- yarn.lock
Fixes #92 
Instead of overwriting env if multiple methods of setting env are used (eg, .env, .cf.bindings, via plugins), merge new values into current values
> fix(dev-server): merge when setting bindings 

- .changeset/soft-cherries-allow.md
- packages/dev-server/src/dev-server.ts
The change is minimal, adding `.mf` to `ignoreWatching` in [`vite-plugins/packages/dev-server/src/dev-server.ts`][ref].
[ref]: https://github.com/tseijp/vite-plugins/blob/main/packages/dev-server/src/dev-server.ts
```ts
// dev-server.ts
- ignoreWatching: [/\.wrangler/],
+ ignoreWatching: [/\.wrangler/, /\.mf/],
```
I've been developing with hono-x and cloudflare d1, but frequently encountered vite errors, causing the server to stop many time.
```ruby
warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
/___/node_modules/wrangler/wrangler-dist/cli.js:29573
throw a;
^
Error: The server is being restarted or closed. Request is …
```
> fix(dev-server): add `.mf` to `ignoreWatching`

- .changeset/tame-rabbits-cross.md
- .github/workflows/ci-dev-server.yml
- packages/dev-server/e2e-bun/e2e.test.ts
- packages/dev-server/e2e-bun/mock/app.ts
- packages/dev-server/e2e-bun/playwright.config.ts
- packages/dev-server/e2e-bun/public/static/hello.json
- packages/dev-server/e2e-bun/vite.config.ts
- packages/dev-server/package.json
- packages/dev-server/src/dev-server.ts
- yarn.lock
Fixes https://github.com/honojs/vite-plugins/issues/107
> feat(dev-server): supports Bun

- .changeset/unlucky-peaches-wave.md
- packages/dev-server/package.json
Fixed a type error when importing with `vite.cofig.ts` due to an incorrect cloudfalre entry in typesVersions in pacakge.json in `@hono/vite-dev-server`.
> fix(dev-server): `typesVersions` cloudflare adapter

- .changeset/strong-worms-rest.md
- packages/dev-server/e2e/e2e.test.ts
- packages/dev-server/e2e/mock/worker.ts
- packages/dev-server/e2e/wrangler.toml
- packages/dev-server/src/adapter/cloudflare.ts
Fixes #125 though currently `caches` does return a cached content.
See: https://developers.cloudflare.com/workers/wrangler/api/
> For the time being, all cache operations do nothing. A more accurate emulation will be made available soon.
> fix(dev-server): add `caches` which to do nothing to cloudflare adapter

- .changeset/moody-islands-wave.md
- packages/cloudflare-pages/README.md
- packages/cloudflare-pages/src/cloudflare-pages.ts
- packages/cloudflare-pages/test/cloudflare-pages.test.ts
- packages/cloudflare-pages/test/project/public-routes-json/_routes.json
Creating a `public/_routes.json` will override the automatic generation.
This is useful when we want to write include/exclude accurately.
> feat(cloudflare-pages): custom `_routes.json`

- .changeset/fair-chefs-sleep.md
- packages/dev-server/README.md
- packages/dev-server/src/dev-server.ts
With this PR, the dev server will use `server.ssrLoadModule` instead of the Runtime API introduced by #129.
The runtime API seems good. But after #129, the problem is that the dev server crashes if the Hono application has an error. Ref #132.
The best solution is to find a way to fix the issue while continuing to use Runtime API. However, I can't find a way, so I'll revert it. In the future, the Vite Enviroment API will be introduced and be stable, we can use it!
Fixes #132
Revert #129
> fix(dev-server): use `ssrLoadModule` instead of Runtime API

- packages/dev-server/README.md
fix small typo in README, the problem was that glob in code example on line 150 was out of sync with the explanation of it on line 141
> docs(readme): Fix small typo in README code example

- .changeset/thin-spies-watch.md
- packages/dev-server/e2e/e2e.test.ts
- packages/dev-server/e2e/mock/worker.ts
- packages/dev-server/src/adapter/cloudflare.ts
> feat(dev-server): support `cf` property in Cloudflare adapter

- .changeset/spotty-gifts-complain.md
- packages/dev-server/README.md
- packages/dev-server/package.json
- yarn.lock
Since dev-server is not required to use cloudflare adapter,
as it so i try to move miniflare dependencies into devDependencies and add them into optional peerDependencies including wrangler.
> fix(dev-server): Move miniflare,wrangler to dev as it peer optional

- .changeset/wild-countries-tan.md
- packages/dev-server/package.json
Fix missing export in package.json
In the recent update i have add very initial bun and node.js adapter but i forget to add exports definition in the package.json so the update does not export module correctly.
https://github.com/honojs/vite-plugins/pull/166
https://github.com/honojs/vite-plugins/pull/167
> fix(dev-server) Missing exports for node,bun adapter

- .changeset/three-pumas-cough.md
- packages/dev-server/src/adapter/cloudflare.ts
* https://github.com/honojs/vite-plugins/issues/172
> fix(dev-server) cloudflare adapter restart

- .changeset/strong-pianos-divide.md
- packages/build/package.json
- packages/build/src/adapter/deno/index.ts
- packages/build/test/deno.test.ts
I added adapter for `Deno` for build plugin.
It uses `Deno.serve`.
```ts
import denoBuildPlugin from '@hono/vite-build/deno'
```
> feat(build): add Deno adapter

- packages/build/README.md
> docs(build): added example project link

- .changeset/fuzzy-books-agree.md
- packages/build/README.md
- packages/build/src/adapter/node/index.ts
- packages/build/test/adapter.test.ts
Fixies #195
This PR will add the `port` option for the `@hono/vite-build/node`.
> feat(build): Node.js adapter supports `port` option

- .changeset/rich-apes-beg.md
- packages/dev-server/e2e-bun/e2e.test.ts
- packages/dev-server/e2e-bun/mock/app.ts
- packages/dev-server/e2e/e2e.test.ts
- packages/dev-server/e2e/mock/worker.ts
- packages/dev-server/src/dev-server.ts
fixes #201 
Hi @usualoma 
Maybe you could have a look at the PR as you've already reviewed my other CSP related PR (https://github.com/honojs/hono/pull/3685). Thanks!
> feat(dev-server): add CSP support for vite's `injectClientScript` option

- .changeset/curly-cherries-tell.md
- packages/ssg/src/ssg.ts
- packages/ssg/test/app.ts
- packages/ssg/test/sample.js
- packages/ssg/test/ssg.test.ts
When using `@hono/vite-ssg` with Vite v6, if the page has dynamic import, the SSR server is closed when resolving the dynamic import and an error occurs.
A reproduction repository can be found at https://github.com/berlysia/sandbox-hono-ssg-vite-v6-dynamic-import.
As a workaround, simply maintain the SSR server until `toSSG` is done.
> [ssg] Preserve the SSR server instance during page rendering

- .changeset/long-panthers-decide.md
- packages/dev-server/e2e/e2e.test.ts
- packages/dev-server/src/dev-server.ts
I was running into an error using honox, this vite dev server plugin, and hono node-server.
The error stack in prod is like
```
file:///app/node_modules/@hono/node-server/dist/index.mjs:345
if (cacheKey in res) {
^
TypeError: Cannot use 'in' operator to search for 'Symbol(cache)' in null
at responseViaResponseObject (file:///app/node_modules/@hono/node-server/dist/index.mjs:345:16)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Node.js v23.3.0
```
I believe that comes from the `cacheKey in res` here https://github.com/honojs/node-server/blob/590fe6cef8a795ea10c300033387f13ed31e144f/src/listener.ts#L86
But that is downstream from calling requestListener to get a Promise<Response>.
Before this change, if the response from the router has `reuest.body === null` …
> fix(dev-server): Fix issue in dev-server where requestListener would return null

- .changeset/tall-teachers-carry.md
- packages/build/README.md
- packages/build/package.json
- packages/build/src/adapter/netlify-functions/index.ts
- packages/build/src/base.ts
- packages/build/src/entry/index.ts
- packages/build/test/adapter.test.ts
- packages/dev-server/e2e-bun/mock/app.ts
- packages/dev-server/e2e/mock/worker.ts
- packages/ssg/test/app.ts
Why?
====
So we can build a bundle targetting the netlify-functions runtime.
How?
====
* Extend `EntryContentOptions` with `entryContentDefaultExportHook` to allow customizing the way the default export of the bundle is built.
* Alter `getEntryContent` to use the `entryContentDefaultExportHook` for defining the default export, defaulting to the previous behavior if not defined.
* Add `netlifyFunctionsBuildPlugin` as a new exported adapter that wraps the hono app in the `hono/netlify` `handle()` adapter and defines a `config` export to make the hono app respond to the root path in Netlify.
Example
====
```ts
// vite.config.ts
import { defineConfig } from "vite";
import devServer from "@hono/vite-dev-server";
import build from "@hono/vite-build/netlify-functions";
export default …
```
> feat(build): Add netlify-functions adapter

- .changeset/green-bulldogs-itch.md
- packages/dev-server/src/dev-server.ts
Fixed problem with source map not working when reading entry files.
fix #227
> Fixed problem with source map not working when reading entry files

- .changeset/proud-rats-flow.md
- packages/ssg/src/ssg.ts
`@hono/vite-ssg` doesn't inherit mode now.
So, it cannot load [`.env.{mode}`](https://vite.dev/guide/env-and-mode.html#env-files) file.
repro: https://stackblitz.com/edit/hono-vite-ssg-mode?file=readme.md
> fix(ssg): inherit mode to load .env.{mode}

- .changeset/selfish-panthers-speak.md
- packages/build/src/adapter/cloudflare-workers/index.ts
- packages/build/test/adapter.test.ts
- packages/build/test/mocks/app-static-files/src/server-fetch-with-handlers.ts
- packages/build/test/mocks/app-static-files/src/server-fetch-with-handlers2.ts
Closes #214
This PR enhances the `@hono/vite-build/cloudflare-workers` adapter to support exporting other Cloudflare Workers event handlers (like `scheduled`, `queue`, etc.) alongside the primary `fetch` handler. This enables the use of features such as Scheduled Events and Queue Consumers with Hono applications built using this plugin.
The adapter now uses Vite plugin hooks (`entryContentAfterHooks` and `entryContentDefaultExportHook`) to inspect the default export(s) from the specified entry file(s). It collects any non-fetch handlers found and merges them into the final worker export object.
**Important:** If the same non-fetch handler (e.g., `scheduled`) is defined in multiple entry files specified in the `entry` option, an error will be thrown to prevent ambiguity and ensure …
> feat(build): support non-fetch handlers for Cloudflare Workers

- .changeset/soft-crews-melt.md
- packages/dev-server/package.json
- yarn.lock
The latest version of `@hono/node-server` resolves the issue of `Failed to find Response internal state key` being logged on dev & build commands in various environments.
For more information: https://github.com/honojs/node-server/issues/240
> chore: bump `@hono/node-server` to 1.14.2

- .changeset/angry-ladybugs-repair.md
- packages/ssg/README.md
- packages/ssg/package.json
- packages/ssg/src/ssg.ts
- packages/ssg/test/ssg.test.ts
- yarn.lock
This pull request adds an interface to accept ssg plugins, a feature introduced in Hono v4.8.0.
Note: Vite plugins and Hono SSG plugins can be very confusing due to their similar naming, so we should be careful with our wording to avoid misunderstandings.
> feat(ssg): add support for ssg plugins
